#* ************************************************************************** *#
#*                                                                            *#
#*                                                        :::      ::::::::   *#
#*   Makefile                                           :+:      :+:    :+:   *#
#*                                                    +:+ +:+         +:+     *#
#*   By: glasset <glasset@student.42.fr>            +#+  +:+       +#+        *#
#*                                                +#+#+#+#+#+   +#+           *#
#*   Created: 2016/10/15 13:03:32 by glasset           #+#    #+#             *#
#*   Updated: 2016/10/15 17:37:07 by glasset          ###   ########.fr       *#
#*                                                                            *#
#* ************************************************************************** *#

RESULT = rush01
SOURCES = player.ml main.ml
PACKS = lablgtk2
LIBS = unix
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
